import express from 'express';
import webpush from 'web-push';
import Database from 'better-sqlite3';
import cron from 'node-cron';
import crypto from 'node:crypto';

const {VAPID_PUBLIC_KEY,VAPID_PRIVATE_KEY,VAPID_SUBJECT,ALLOWED_ORIGIN,PORT='3000',DB_FILE='./prayer-push.sqlite'}=process.env;
if(!VAPID_PUBLIC_KEY||!VAPID_PRIVATE_KEY||!VAPID_SUBJECT||!ALLOWED_ORIGIN)throw Error('Missing VAPID or ALLOWED_ORIGIN environment settings');
webpush.setVapidDetails(VAPID_SUBJECT,VAPID_PUBLIC_KEY,VAPID_PRIVATE_KEY);
const db=new Database(DB_FILE);db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS subscribers(id TEXT PRIMARY KEY, endpoint TEXT NOT NULL UNIQUE, subscription TEXT NOT NULL, latitude REAL NOT NULL, longitude REAL NOT NULL, method INTEGER NOT NULL, offset INTEGER NOT NULL, lead INTEGER NOT NULL, enabled TEXT NOT NULL, timezone TEXT NOT NULL, updated_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS deliveries(id TEXT PRIMARY KEY, sent_at INTEGER NOT NULL);`);
const app=express();app.disable('x-powered-by');app.use(express.json({limit:'12kb'}));
app.use((req,res,next)=>{res.setHeader('Vary','Origin');if(req.headers.origin===ALLOWED_ORIGIN){res.setHeader('Access-Control-Allow-Origin',ALLOWED_ORIGIN);res.setHeader('Access-Control-Allow-Methods','GET,POST,DELETE,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');}if(req.method==='OPTIONS')return res.sendStatus(204);if(req.headers.origin!==ALLOWED_ORIGIN&&req.path!=='/health')return res.status(403).json({error:'origin_not_allowed'});next()});
const names=['Fajr','Dhuhr','Asr','Maghrib','Isha'];
const limit=new Map();app.use('/api',(req,res,next)=>{const id=req.ip;const now=Date.now();const x=limit.get(id)||{n:0,start:now};if(now-x.start>60000){x.n=0;x.start=now}if(++x.n>35)return res.status(429).json({error:'rate_limited'});limit.set(id,x);next()});
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
function validate(x){const s=x?.subscription;if(!s||typeof s.endpoint!=='string'||!s.endpoint.startsWith('https://')||!s.keys?.auth||!s.keys?.p256dh||s.endpoint.length>2048)throw Error('invalid_subscription');const lat=Number(x.latitude),lon=Number(x.longitude),method=Number(x.method),offset=Number(x.offset),lead=Number(x.lead);if(!Number.isFinite(lat)||Math.abs(lat)>90||!Number.isFinite(lon)||Math.abs(lon)>180||![19,3,4,5,18,21].includes(method)||!Number.isInteger(offset)||Math.abs(offset)>10||![0,5,10,15].includes(lead)||!Array.isArray(x.enabled)||x.enabled.some(p=>!names.includes(p)))throw Error('invalid_settings');return {s,lat,lon,method,offset,lead,enabled:[...new Set(x.enabled)]}}
app.get('/health',(_req,res)=>res.json({ok:true}));
app.get('/api/public-key',(_req,res)=>res.json({publicKey:VAPID_PUBLIC_KEY}));
app.post('/api/subscriptions',(req,res)=>{try{const v=validate(req.body);const id=hash(v.s.endpoint),existing=db.prepare('SELECT timezone FROM subscribers WHERE id=?').get(id);db.prepare('INSERT INTO subscribers(id,endpoint,subscription,latitude,longitude,method,offset,lead,enabled,timezone,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET subscription=excluded.subscription,latitude=excluded.latitude,longitude=excluded.longitude,method=excluded.method,offset=excluded.offset,lead=excluded.lead,enabled=excluded.enabled,updated_at=excluded.updated_at').run(id,v.s.endpoint,JSON.stringify(v.s),v.lat,v.lon,v.method,v.offset,v.lead,JSON.stringify(v.enabled),existing?.timezone||'Africa/Algiers',Date.now());res.json({ok:true})}catch{res.status(400).json({error:'invalid_data'})}});
app.delete('/api/subscriptions', (req,res)=>{const endpoint=req.body?.endpoint;if(typeof endpoint!=='string')return res.status(400).json({error:'invalid_data'});db.prepare('DELETE FROM subscribers WHERE id=?').run(hash(endpoint));res.json({ok:true})});
function localParts(now,tz){const p=new Intl.DateTimeFormat('en-GB',{timeZone:tz,hour:'2-digit',minute:'2-digit',year:'numeric',month:'2-digit',day:'2-digit',hourCycle:'h23'}).formatToParts(now);const o=Object.fromEntries(p.map(x=>[x.type,x.value]));return {date:o.year+'-'+o.month+'-'+o.day,minute:Number(o.hour)*60+Number(o.minute)}}
const timeMinutes=v=>{const m=/^(\d{2}):(\d{2})/.exec(v||'');return m?Number(m[1])*60+Number(m[2]):NaN};
const cache=new Map();
async function timings(row,date){const k=[date,row.latitude.toFixed(4),row.longitude.toFixed(4),row.method].join(':');if(cache.has(k))return cache.get(k);const [year,month,day]=date.split('-');const u=new URL('https://api.aladhan.com/v1/timings/'+day+'-'+month+'-'+year);u.searchParams.set('latitude',row.latitude);u.searchParams.set('longitude',row.longitude);u.searchParams.set('method',row.method);const response=await fetch(u,{signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error('prayer_api');const j=await response.json();if(j.code!==200||!j.data?.meta?.timezone)throw Error('prayer_data');const value={times:j.data.timings,zone:j.data.meta.timezone};cache.set(k,value);return value}
let running=false;
async function processAlerts(){if(running)return;running=true;try{const now=new Date(),rows=db.prepare('SELECT * FROM subscribers').all();for(const row of rows){try{
  // For initial synchronization derive timezone from the prayer source, not the visitor's device.
  let local=localParts(now,row.timezone),result=await timings(row,local.date);
  if(result.zone!==row.timezone){db.prepare('UPDATE subscribers SET timezone=? WHERE id=?').run(result.zone,row.id);local=localParts(now,result.zone);result=await timings(row,local.date)}
  for(const prayer of JSON.parse(row.enabled)){const t=timeMinutes(result.times[prayer]);if(!Number.isFinite(t))continue;for(const [mode,at] of [['at',t+row.offset],...(row.lead?[['before',t+row.offset-row.lead]]:[])]){if(local.minute!==at)continue;const key=hash(row.id+local.date+prayer+mode+row.method+row.offset+row.lead);if(db.prepare('SELECT 1 FROM deliveries WHERE id=?').get(key))continue;db.prepare('INSERT OR IGNORE INTO deliveries(id,sent_at) VALUES(?,?)').run(key,Date.now());const labels={Fajr:'الفجر',Dhuhr:'الظهر',Asr:'العصر',Maghrib:'المغرب',Isha:'العشاء'};try{await webpush.sendNotification(JSON.parse(row.subscription),JSON.stringify({title:mode==='before'?'اقترب وقت صلاة '+labels[prayer]:'حان وقت صلاة '+labels[prayer],body:'تذكير مواقيت الصلاة',url:'https://imadtbn.github.io/quran-mp3/prayer-times.html',tag:'prayer-'+key}),{TTL:600,urgency:'high'})}catch(e){if([404,410].includes(e.statusCode))db.prepare('DELETE FROM subscribers WHERE id=?').run(row.id);else console.error('Push delivery failed:',e.statusCode||e.message)}}}}
 }catch(e){console.error('Schedule error:',e.message)}}db.prepare('DELETE FROM deliveries WHERE sent_at<?').run(Date.now()-8*86400000);if(cache.size>3000)cache.clear()}finally{running=false}}
cron.schedule('* * * * *',()=>processAlerts().catch(console.error));app.listen(Number(PORT),()=>console.log('Prayer push server listening'));